export interface ConceptNode {
  key: string;
  name: string;
  category: 'Foundations' | 'Tactics' | 'Strategy' | 'Endgames';
  difficulty: number;
  importance: number;
  prerequisites: string[]; // keys of prerequisite concepts
  relatedConcepts: string[];
}

export const CONCEPT_GRAPH: Record<string, ConceptNode> = {
  CHESS_BOARD: {
    key: 'CHESS_BOARD',
    name: 'The Chessboard & Coordinates',
    category: 'Foundations',
    difficulty: 1,
    importance: 5,
    prerequisites: [],
    relatedConcepts: ['PIECE_MOVEMENT'],
  },
  PIECE_MOVEMENT: {
    key: 'PIECE_MOVEMENT',
    name: 'Piece Movements',
    category: 'Foundations',
    difficulty: 1,
    importance: 5,
    prerequisites: ['CHESS_BOARD'],
    relatedConcepts: ['CAPTURING'],
  },
  CAPTURING: {
    key: 'CAPTURING',
    name: 'Capturing & Value',
    category: 'Foundations',
    difficulty: 1,
    importance: 5,
    prerequisites: ['PIECE_MOVEMENT'],
    relatedConcepts: ['CHECK'],
  },
  CHECK: {
    key: 'CHECK',
    name: 'Check & King Safety',
    category: 'Foundations',
    difficulty: 1,
    importance: 5,
    prerequisites: ['CAPTURING'],
    relatedConcepts: ['CHECKMATE'],
  },
  CHECKMATE: {
    key: 'CHECKMATE',
    name: 'Checkmate Mechanics',
    category: 'Foundations',
    difficulty: 2,
    importance: 5,
    prerequisites: ['CHECK'],
    relatedConcepts: ['BACK_RANK_MATE', 'STALEMATE'],
  },
  STALEMATE: {
    key: 'STALEMATE',
    name: 'Stalemate & Draws',
    category: 'Foundations',
    difficulty: 2,
    importance: 4,
    prerequisites: ['CHECKMATE'],
    relatedConcepts: ['OPPOSITION'],
  },
  PIN: {
    key: 'PIN',
    name: 'Absolute & Relative Pins',
    category: 'Tactics',
    difficulty: 2,
    importance: 5,
    prerequisites: ['CHECK', 'CAPTURING'],
    relatedConcepts: ['SKEWER', 'REMOVING_DEFENDER'],
  },
  SKEWER: {
    key: 'SKEWER',
    name: 'Skewers & X-Rays',
    category: 'Tactics',
    difficulty: 2,
    importance: 4,
    prerequisites: ['PIN'],
    relatedConcepts: ['PIN', 'DISCOVERED_ATTACK'],
  },
  FORK: {
    key: 'FORK',
    name: 'Knight & Double Forks',
    category: 'Tactics',
    difficulty: 2,
    importance: 5,
    prerequisites: ['PIECE_MOVEMENT', 'CAPTURING'],
    relatedConcepts: ['DOUBLE_ATTACK'],
  },
  BACK_RANK_MATE: {
    key: 'BACK_RANK_MATE',
    name: 'Back Rank Mates',
    category: 'Tactics',
    difficulty: 2,
    importance: 5,
    prerequisites: ['CHECKMATE'],
    relatedConcepts: ['DEFLECTION', 'CLEARANCE'],
  },
  DISCOVERED_ATTACK: {
    key: 'DISCOVERED_ATTACK',
    name: 'Discovered Attacks',
    category: 'Tactics',
    difficulty: 3,
    importance: 4,
    prerequisites: ['PIN', 'CHECK'],
    relatedConcepts: ['DOUBLE_ATTACK'],
  },
  DEFLECTION: {
    key: 'DEFLECTION',
    name: 'Deflection & Overloading',
    category: 'Tactics',
    difficulty: 3,
    importance: 4,
    prerequisites: ['PIN', 'BACK_RANK_MATE'],
    relatedConcepts: ['DECOY', 'CLEARANCE'],
  },
  CENTER_CONTROL: {
    key: 'CENTER_CONTROL',
    name: 'Center Control (e4, d4, e5, d5)',
    category: 'Strategy',
    difficulty: 2,
    importance: 4,
    prerequisites: ['PIECE_MOVEMENT'],
    relatedConcepts: ['DEVELOPMENT'],
  },
  DEVELOPMENT: {
    key: 'DEVELOPMENT',
    name: 'Rapid Development & Tempo',
    category: 'Strategy',
    difficulty: 2,
    importance: 4,
    prerequisites: ['CENTER_CONTROL'],
    relatedConcepts: ['KING_SAFETY'],
  },
  CASTLING: {
    key: 'CASTLING',
    name: 'Castling & King Safety',
    category: 'Foundations',
    difficulty: 2,
    importance: 5,
    prerequisites: ['CHECK', 'PIECE_MOVEMENT'],
    relatedConcepts: ['KING_SAFETY'],
  },
  EN_PASSANT: {
    key: 'EN_PASSANT',
    name: 'En Passant',
    category: 'Foundations',
    difficulty: 2,
    importance: 4,
    prerequisites: ['PIECE_MOVEMENT', 'CAPTURING'],
    relatedConcepts: ['PAWN_PROMOTION'],
  },
  PAWN_PROMOTION: {
    key: 'PAWN_PROMOTION',
    name: 'Pawn Promotion',
    category: 'Foundations',
    difficulty: 2,
    importance: 5,
    prerequisites: ['PIECE_MOVEMENT'],
    relatedConcepts: ['PASSED_PAWNS'],
  },
  PIECE_VALUES: {
    key: 'PIECE_VALUES',
    name: 'Piece Values & Exchanges',
    category: 'Foundations',
    difficulty: 1,
    importance: 5,
    prerequisites: ['CAPTURING'],
    relatedConcepts: ['FORK'],
  },
  SMOTHERED_MATE: {
    key: 'SMOTHERED_MATE',
    name: 'Smothered Mate',
    category: 'Tactics',
    difficulty: 3,
    importance: 4,
    prerequisites: ['FORK', 'CHECKMATE'],
    relatedConcepts: ['BACK_RANK_MATE', 'DEFLECTION'],
  },
  PASSED_PAWNS: {
    key: 'PASSED_PAWNS',
    name: 'Passed Pawns',
    category: 'Endgames',
    difficulty: 2,
    importance: 5,
    prerequisites: ['PAWN_PROMOTION', 'OPPOSITION'],
    relatedConcepts: ['OPPOSITION'],
  },
  OPPOSITION: {
    key: 'OPPOSITION',
    name: 'King Opposition & Pawns',
    category: 'Endgames',
    difficulty: 3,
    importance: 4,
    prerequisites: ['CHECKMATE', 'STALEMATE'],
    relatedConcepts: ['PASSED_PAWNS'],
  },
  // ==========================================
  // OPENINGS REPERTOIRES (CLASSICAL & HYPERMODERN)
  // ==========================================
  OPENING_PRINCIPLES: {
    key: 'OPENING_PRINCIPLES',
    name: 'Opening Principles',
    category: 'Strategy',
    difficulty: 1,
    importance: 5,
    prerequisites: ['CENTER_CONTROL', 'DEVELOPMENT'],
    relatedConcepts: ['ITALIAN_GAME', 'RUY_LOPEZ'],
  },
  ITALIAN_GAME: {
    key: 'ITALIAN_GAME',
    name: 'The Italian Game',
    category: 'Strategy',
    difficulty: 1,
    importance: 5,
    prerequisites: ['OPENING_PRINCIPLES', 'DEVELOPMENT'],
    relatedConcepts: ['RUY_LOPEZ'],
  },
  RUY_LOPEZ: {
    key: 'RUY_LOPEZ',
    name: 'The Ruy Lopez',
    category: 'Strategy',
    difficulty: 2,
    importance: 5,
    prerequisites: ['OPENING_PRINCIPLES', 'PIN'],
    relatedConcepts: ['ITALIAN_GAME'],
  },
  SCOTCH_GAME: {
    key: 'SCOTCH_GAME',
    name: 'The Scotch Game',
    category: 'Strategy',
    difficulty: 2,
    importance: 4,
    prerequisites: ['OPENING_PRINCIPLES'],
    relatedConcepts: ['ITALIAN_GAME'],
  },
  SICILIAN_DEFENSE: {
    key: 'SICILIAN_DEFENSE',
    name: 'The Sicilian Defense',
    category: 'Strategy',
    difficulty: 3,
    importance: 5,
    prerequisites: ['OPENING_PRINCIPLES', 'PAWN_STRUCTURE'],
    relatedConcepts: ['FRENCH_DEFENSE'],
  },
  FRENCH_DEFENSE: {
    key: 'FRENCH_DEFENSE',
    name: 'The French Defense',
    category: 'Strategy',
    difficulty: 2,
    importance: 4,
    prerequisites: ['PAWN_STRUCTURE', 'OPENING_PRINCIPLES'],
    relatedConcepts: ['CARO_KANN'],
  },
  CARO_KANN: {
    key: 'CARO_KANN',
    name: 'The Caro-Kann Defense',
    category: 'Strategy',
    difficulty: 2,
    importance: 4,
    prerequisites: ['PAWN_STRUCTURE', 'OPENING_PRINCIPLES'],
    relatedConcepts: ['SLAV_DEFENSE'],
  },
  QUEENS_GAMBIT: {
    key: 'QUEENS_GAMBIT',
    name: 'The Queen’s Gambit',
    category: 'Strategy',
    difficulty: 2,
    importance: 5,
    prerequisites: ['CENTER_CONTROL', 'OPENING_PRINCIPLES'],
    relatedConcepts: ['SLAV_DEFENSE', 'CATALAN_OPENING'],
  },
  SLAV_DEFENSE: {
    key: 'SLAV_DEFENSE',
    name: 'The Slav Defense',
    category: 'Strategy',
    difficulty: 2,
    importance: 4,
    prerequisites: ['QUEENS_GAMBIT', 'PAWN_STRUCTURE'],
    relatedConcepts: ['CARO_KANN'],
  },
  LONDON_SYSTEM: {
    key: 'LONDON_SYSTEM',
    name: 'The London System',
    category: 'Strategy',
    difficulty: 1,
    importance: 4,
    prerequisites: ['OPENING_PRINCIPLES'],
    relatedConcepts: ['QUEENS_GAMBIT'],
  },
  KINGS_INDIAN: {
    key: 'KINGS_INDIAN',
    name: 'The King’s Indian Defense',
    category: 'Strategy',
    difficulty: 3,
    importance: 5,
    prerequisites: ['FIANCHETTO', 'PAWN_STRUCTURE'],
    relatedConcepts: ['GRUNFELD', 'PIRC_DEFENSE'],
  },
  NIMZO_INDIAN: {
    key: 'NIMZO_INDIAN',
    name: 'The Nimzo-Indian Defense',
    category: 'Strategy',
    difficulty: 3,
    importance: 5,
    prerequisites: ['PIN', 'PAWN_STRUCTURE'],
    relatedConcepts: ['QUEENS_GAMBIT', 'CATALAN_OPENING'],
  },
  GRUNFELD: {
    key: 'GRUNFELD',
    name: 'The Grünfeld Defense',
    category: 'Strategy',
    difficulty: 4,
    importance: 4,
    prerequisites: ['FIANCHETTO', 'CENTER_CONTROL'],
    relatedConcepts: ['KINGS_INDIAN'],
  },
  ENGLISH_OPENING: {
    key: 'ENGLISH_OPENING',
    name: 'The English Opening & Réti',
    category: 'Strategy',
    difficulty: 3,
    importance: 4,
    prerequisites: ['FIANCHETTO', 'OPENING_PRINCIPLES'],
    relatedConcepts: ['CATALAN_OPENING'],
  },
  ALEKHINE_DEFENSE: {
    key: 'ALEKHINE_DEFENSE',
    name: 'Alekhine’s Defense',
    category: 'Strategy',
    difficulty: 3,
    importance: 4,
    prerequisites: ['PAWN_STRUCTURE', 'OPENING_PRINCIPLES'],
    relatedConcepts: ['SCANDINAVIAN_DEFENSE'],
  },
  PIRC_DEFENSE: {
    key: 'PIRC_DEFENSE',
    name: 'The Pirc & Modern Defenses',
    category: 'Strategy',
    difficulty: 2,
    importance: 4,
    prerequisites: ['FIANCHETTO', 'OPENING_PRINCIPLES'],
    relatedConcepts: ['KINGS_INDIAN'],
  },
  CATALAN_OPENING: {
    key: 'CATALAN_OPENING',
    name: 'The Catalan Opening',
    category: 'Strategy',
    difficulty: 3,
    importance: 4,
    prerequisites: ['QUEENS_GAMBIT', 'FIANCHETTO'],
    relatedConcepts: ['ENGLISH_OPENING'],
  },
  MODERN_BENONI: {
    key: 'MODERN_BENONI',
    name: 'The Modern Benoni',
    category: 'Strategy',
    difficulty: 4,
    importance: 4,
    prerequisites: ['FIANCHETTO', 'PAWN_STRUCTURE'],
    relatedConcepts: ['KINGS_INDIAN'],
  },
  KINGS_INDIAN_ATTACK: {
    key: 'KINGS_INDIAN_ATTACK',
    name: 'The King’s Indian Attack',
    category: 'Strategy',
    difficulty: 2,
    importance: 4,
    prerequisites: ['FIANCHETTO', 'OPENING_PRINCIPLES'],
    relatedConcepts: ['KINGS_INDIAN'],
  },
  LARSENS_OPENING: {
    key: 'LARSENS_OPENING',
    name: 'Larsen’s Opening',
    category: 'Strategy',
    difficulty: 3,
    importance: 3,
    prerequisites: ['FIANCHETTO', 'OPENING_PRINCIPLES'],
    relatedConcepts: ['ENGLISH_OPENING'],
  },
  SCANDINAVIAN_DEFENSE: {
    key: 'SCANDINAVIAN_DEFENSE',
    name: 'The Scandinavian Defense',
    category: 'Strategy',
    difficulty: 2,
    importance: 4,
    prerequisites: ['OPENING_PRINCIPLES'],
    relatedConcepts: ['CARO_KANN'],
  },
};

export class ConceptGraphService {
  public static getPrerequisites(conceptKey: string): string[] {
    return CONCEPT_GRAPH[conceptKey]?.prerequisites || [];
  }

  /**
   * Explores root causes: If user is struggling with concept, checks if prerequisites are weak
   */
  public static findRootWeakness(
    failedConceptKey: string,
    userMasteryMap: Record<string, number>
  ): string {
    const node = CONCEPT_GRAPH[failedConceptKey];
    if (!node || node.prerequisites.length === 0) return failedConceptKey;

    for (const prereq of node.prerequisites) {
      const prereqMastery = userMasteryMap[prereq] ?? 100;
      if (prereqMastery < 60) {
        // Root prerequisite is failing, remediate this first!
        return prereq;
      }
    }

    return failedConceptKey;
  }
}
